[tool.poetry]
name = "anydep"
version = "0.1.0"
description = "Dependency Injection, backed by AnyIO"
authors = ["Adrian Garcia Badaracco <adrian@adriangb.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
anyio = "~3"

[tool.poetry.group.dev.dependencies]
dacite = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "~6"
pre-commit = "~2"
pytest-cov = { version = "~2", extras = ["toml"] }
pytest-sugar = "~0"
trio = "~0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.coverage.run]
source = ["anydep"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover"]

[tool.pytest.ini_options]
testpaths = ["tests"]
