[tool.poetry]
name = "di"
version = "0.1.0-alpha"
description = "Dependency Injection, backed by AnyIO"
authors = ["Adrian Garcia Badaracco <adrian@adriangb.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
anyio = "~3"

[tool.poetry.group.dev.dependencies]
pytest = "~6"
pre-commit = "~2"
pytest-cov = { version = "~2", extras = ["toml"] }
pytest-sugar = "~0"
trio = "~0"
mkdocs = "~1"
mkdocs-material = "~7"
mkautodoc = "~0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["di", "tests"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "\\.\\.\\.\n", "raise NotImplementedError"]

[tool.pytest.ini_options]
testpaths = ["tests"]
