name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.2.0
        with:
          version: 1.2.0a2
          virtualenvs-in-project: true
      - name: Deploy docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          make docs-deploy
