name: CI/CD

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Lint
        run: make lint
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Test
        run: make test
      - name: Export Coverage Report
        run: pip install "coverage[toml]" && coverage xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: di
          env_vars: OS,PYTHON
          fail_ci_if_error: true
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: current
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
          fetch-depth: 0
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Check versions
        run: |
          cd $GITHUB_WORKSPACE/current
          CURRENT_VERSION=$(poetry version -s)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/main
          PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
          VERSION_BUMPED=false; [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ] && VERSION_BUMPED=true
          echo "VERSION_BUMPED=$VERSION_BUMPED" >> $GITHUB_ENV
  version-bump:
    runs-on: ubuntu-latest
    # only for PRs
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check for source code changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '*.py'
      - name: Enforce version bump
        if: steps.changes.outputs.src == 'true'
        run: |
          python -c "from packaging import version;assert version.parse(\"${NEW_VERSION}\") > version.parse(\"${OLD_VERSION}\"), \"❌ Bad version bump detected: you must bump the version in pyproject.toml if making source code changes\""
          python -c "print(\"✅ Version will be bumped from ${OLD_VERSION} to ${NEW_VERSION}\")"
  docs:
    if: github.ref == 'refs/heads/main'
    concurrency: docs-branch
    name: 🚀 Deploy Docs 📄
    runs-on: ubuntu-latest
    needs: ["test", "lint"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Deploy docs
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          make docs-deploy
  pypi:
    if: ${{ env.VERSION_BUMPED }} == 'true' && github.ref == 'refs/heads/main'
    name: 🚀 PyPi Release 📦
    runs-on: ubuntu-latest
    needs: ["test", "lint"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
      - name: Check version bump
        run: |
          NEW_VERSION=$(poetry version -s)
          OLD_VERSION=$(git describe --tags --abbrev=0)
          VERSION_BUMPED=false; [ "$NEW_VERSION" != "$OLD_VERSION" ] && VERSION_BUMPED=true
          echo "VERSION_BUMPED=$VERSION_BUMPED" >> $GITHUB_ENV
      - name: Release on PyPi
        run: |
          PACKAGE_VERSION=$(poetry version -s)
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_ENV
          printf "\nSee this release on GitHub: [v$PACKAGE_VERSION](https://github.com/adriangb/di/releases/tag/$PACKAGE_VERSION)\n" >> README.md
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build
      - name: 🚀 Create GitHub Release 😺
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.package_version }}
          generateReleaseNotes: true
